language: node_js
if: tag IS present
deploy:
  provider: npm
  email: maxkarpawich@gmail.com
  api_key:
    secure: DQ2ejJKh5sND2CTB731SdS8n7eXrlab5yYKQwNUhD3f9YbQOOL0BPCkrvU7v0guGk9reqWD4KGvhSjc3WP8P/FoVH2KDGftd8pNOlsFQFDhnSvT3yNIWOx1oAMpkV99dDYUTxSqvwg9uECDKZH3BhGxtFvyumn443FD38x/tjLpIclTrklSIiAj9HpkmH8y+ql4idKIIBdsUu1Wwc/ugKJHwS+uD6oLx4WLXWpiPkCSSAT4t5RaZg09ZypMN5rZ9Xfgn09TJMzsDdcz5/ZczTykWFxKCvaMQGLYaCff3QJfPrC7umhGb6fdADBaPVvEK8yNEruO/U0lmLC2C+ZT6ZFxOMmw1E0TfdzdEfzP/VjqwT9ODPvHR0Dl9YIL3tZxRIxPyPYlUvP9oFtpfOpu+9/hhBzlhWb//x7Fiaj/6Z0q8bFRKIIpeqHzUk4Srfzz5hkwe77jfVZT974983Pp9U8NJnbgo+gPyuJqPDiCaE87M99cFOR043bAR+9H5npYGfOUpI4w1ruNKQcBzwkd0d5uG09XPAlRl5SKso/PhiEtbOertCXgmQHr6GinzVLQiRIAl/Ze3HMRl0qPrLQ8C17Bj3l2iE8FYjac64/lgfl2zd+KO9gWYnNd8H1lGudtCjpkCXSEU9a64a4MvGlv1XL6wIg9Z+8DSeikxdWRR4jU=
  skip_cleanup: true
  on:
    tags: true
