language: node_js
if: tag IS present
deploy:
  provider: npm
  email: maxkarpawich@gmail.com
  api_key:
    secure: K5mXJYDgUewPo3vj0I+AGLHGZe1oQIsU/dRLsW8lWGqDcHxoLu9kexTdupshR7JTUDV3QykNU20J33eOj0soBxJXfPK/gTtbGmmEKTbhrwvFzyYkTNsRCMFddDYFsaBNxDtIyVcAsDqEIQ0y9U9ySLi0yn0J5LLFDA5zJ5aqPfiPh/Zv5K6gKQNKfXHq+oSDiVLZirchPa9uKrbLQMCrCrlquP5PygIvNBljhXG+KY91R9conJF6oMpJVsoRi7oCKQEMifBRrcp4XKwtVyo5MpefMCrRVI/BjgJwFCo7wbWERmchiuE2PSAu33OK5zIJKbwxJCQOw1EsPN+EpORtfTUpAh4pWBJfrL78PgOjFLEfxmcNVCOQHscHsRYyxc0SI8pl4obEvxZoFyjjUimYaeOSbqghyS3IQysxN6VWDQuWL1YbY0HZvuf5cL8d/u5z4a2lCwMK5eDz1ujEtquldXG9j57mAjPEPAp41OFoDTmjaS0Sd6zZUcD52+QqJGCUUuk3ZbI2ajqmJ4MC8WgGgpE3g/Sw8Fm5nKMM4TnD2YbIRfnPwtd7IJ9kfxWNg9oxyh6c4CJaty8R+0fnkO60ow2ahicBvP/Zh/CGFOsR/hF3dwp+Lp+H9t0f5H5EIQscbosP6WYc4XZKkXdfWQdXPmR4FC7LgJFa93rQZzbgPfA=
  on:
    tags: true
